### ISSUE TITLE
enforce team composition on roster page

### ISSUE THREAD

**Issue by Exploding** [Exploding/FantasyOWL#3]

**Comment by rahulgi** [comment]
what's the required roster comp?

**Comment by erictango** [comment]
> 
> 
> what's the required roster comp?

1/1/2(support)/2(flex) ?

**Comment by Exploding** [comment]
make it configurable maybe? default 1/1/1/3 flex?

**Comment by rahulgi** [comment]
@Janitaliaa did you say this was done?
